# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: statestore
# spec:
#   type: state.redis
#   metadata:
#   - name: redisHost
#     value: localhost:6379
#   - name: redisPassword
#     value: ""
#   - name: actorStateStore
#     value: "true"
# scopes:
# - trafficcontrolservice

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-dapr-ussc-demo.redis.cache.windows.net:6380
  - name: redisPassword
    value: Xpw5IoyqF9uadcwv7E1dA1jIFeU6ZqwpLAzCaPKwbsk=
  - name: actorStateStore
    value: true
  - name: enableTLS
    value: true
scopes:
- trafficcontrolservice